[2024-06-25T12:25:08.466+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-25T12:25:08.499+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_dag_for_alerting_final_1.check_previous_run_status manual__2024-06-25T12:25:06.981147+00:00 [queued]>
[2024-06-25T12:25:08.510+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_dag_for_alerting_final_1.check_previous_run_status manual__2024-06-25T12:25:06.981147+00:00 [queued]>
[2024-06-25T12:25:08.510+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-06-25T12:25:08.528+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): check_previous_run_status> on 2024-06-25 12:25:06.981147+00:00
[2024-06-25T12:25:08.538+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1497) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-25T12:25:08.540+0000] {standard_task_runner.py:63} INFO - Started process 1498 to run task
[2024-06-25T12:25:08.540+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'demo_dag_for_alerting_final_1', 'check_previous_run_status', 'manual__2024-06-25T12:25:06.981147+00:00', '--job-id', '3889', '--raw', '--subdir', 'DAGS_FOLDER/demo_dag_for_alerting.py', '--cfg-path', '/tmp/tmp0b3np9oq']
[2024-06-25T12:25:08.541+0000] {standard_task_runner.py:91} INFO - Job 3889: Subtask check_previous_run_status
[2024-06-25T12:25:08.600+0000] {task_command.py:426} INFO - Running <TaskInstance: demo_dag_for_alerting_final_1.check_previous_run_status manual__2024-06-25T12:25:06.981147+00:00 [running]> on host ced2311e92d2
[2024-06-25T12:25:08.759+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='demo_dag_for_alerting_final_1' AIRFLOW_CTX_TASK_ID='check_previous_run_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T12:25:06.981147+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-25T12:25:06.981147+00:00'
[2024-06-25T12:25:08.760+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-25T12:25:08.791+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-06-25T12:25:08.813+0000] {helper_functions.py:103} ERROR - Error interacting with the database: name '***_api_config' is not defined
[2024-06-25T12:25:08.813+0000] {helper_functions.py:112} ERROR - Failed to run demo_dag_for_alerting_final_1 with task check_previous_run_status: data must be bytes
[2024-06-25T12:25:08.814+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-25T12:25:08.816+0000] {branch.py:36} INFO - Branch into None
[2024-06-25T12:25:08.816+0000] {skipmixin.py:178} INFO - Following branch None
[2024-06-25T12:25:08.839+0000] {skipmixin.py:246} INFO - Skipping tasks [('skip_run', -1), ('start_run', -1)]
[2024-06-25T12:25:08.885+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-25T12:25:08.902+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=demo_dag_for_alerting_final_1, task_id=check_previous_run_status, run_id=manual__2024-06-25T12:25:06.981147+00:00, execution_date=20240625T122506, start_date=20240625T122508, end_date=20240625T122508
[2024-06-25T12:25:08.956+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-25T12:25:08.991+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-25T12:25:08.996+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
