[2024-06-21T08:37:05.637+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-21T08:37:05.663+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_dag_for_alerting_final_1.insert_new_record_into_audit_table scheduled__2024-06-21T08:36:00+00:00 [queued]>
[2024-06-21T08:37:05.673+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_dag_for_alerting_final_1.insert_new_record_into_audit_table scheduled__2024-06-21T08:36:00+00:00 [queued]>
[2024-06-21T08:37:05.674+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-06-21T08:37:05.688+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_new_record_into_audit_table> on 2024-06-21 08:36:00+00:00
[2024-06-21T08:37:05.692+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4392) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-21T08:37:05.693+0000] {standard_task_runner.py:63} INFO - Started process 4393 to run task
[2024-06-21T08:37:05.694+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'demo_dag_for_alerting_final_1', 'insert_new_record_into_audit_table', 'scheduled__2024-06-21T08:36:00+00:00', '--job-id', '3276', '--raw', '--subdir', 'DAGS_FOLDER/demo_dag_for_alerting.py', '--cfg-path', '/tmp/tmpxbol6330']
[2024-06-21T08:37:05.695+0000] {standard_task_runner.py:91} INFO - Job 3276: Subtask insert_new_record_into_audit_table
[2024-06-21T08:37:05.733+0000] {task_command.py:426} INFO - Running <TaskInstance: demo_dag_for_alerting_final_1.insert_new_record_into_audit_table scheduled__2024-06-21T08:36:00+00:00 [running]> on host e66744caf823
[2024-06-21T08:37:05.816+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='demo_dag_for_alerting_final_1' AIRFLOW_CTX_TASK_ID='insert_new_record_into_audit_table' AIRFLOW_CTX_EXECUTION_DATE='2024-06-21T08:36:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-21T08:36:00+00:00'
[2024-06-21T08:37:05.817+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-21T08:37:05.830+0000] {logging_mixin.py:188} INFO - insert_into_audit_table_for_adhoc_data
[2024-06-21T08:37:05.830+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-21T08:37:05.830+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-21T08:37:05.838+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=demo_dag_for_alerting_final_1, task_id=insert_new_record_into_audit_table, run_id=scheduled__2024-06-21T08:36:00+00:00, execution_date=20240621T083600, start_date=20240621T083705, end_date=20240621T083705
[2024-06-21T08:37:05.867+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-21T08:37:05.884+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-21T08:37:05.885+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
