[2024-06-25T09:47:39.173+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-25T09:47:39.208+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_dag_for_alerting_apis_final.check_data_in_stream manual__2024-06-25T09:47:33.926111+00:00 [queued]>
[2024-06-25T09:47:39.220+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_dag_for_alerting_apis_final.check_data_in_stream manual__2024-06-25T09:47:33.926111+00:00 [queued]>
[2024-06-25T09:47:39.221+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-06-25T09:47:39.238+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): check_data_in_stream> on 2024-06-25 09:47:33.926111+00:00
[2024-06-25T09:47:39.243+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=386) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-25T09:47:39.244+0000] {standard_task_runner.py:63} INFO - Started process 387 to run task
[2024-06-25T09:47:39.244+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'demo_dag_for_alerting_apis_final', 'check_data_in_stream', 'manual__2024-06-25T09:47:33.926111+00:00', '--job-id', '3752', '--raw', '--subdir', 'DAGS_FOLDER/demo_dag_for_alerting_apis.py', '--cfg-path', '/tmp/tmpi_pn941t']
[2024-06-25T09:47:39.245+0000] {standard_task_runner.py:91} INFO - Job 3752: Subtask check_data_in_stream
[2024-06-25T09:47:39.290+0000] {task_command.py:426} INFO - Running <TaskInstance: demo_dag_for_alerting_apis_final.check_data_in_stream manual__2024-06-25T09:47:33.926111+00:00 [running]> on host ced2311e92d2
[2024-06-25T09:47:39.407+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='demo_dag_for_alerting_apis_final' AIRFLOW_CTX_TASK_ID='check_data_in_stream' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T09:47:33.926111+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-25T09:47:33.926111+00:00'
[2024-06-25T09:47:39.407+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-25T09:47:39.422+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-06-25T09:47:39.422+0000] {python.py:237} INFO - Done. Returned value was: insert_new_record_into_audit_table
[2024-06-25T09:47:39.423+0000] {branch.py:36} INFO - Branch into insert_new_record_into_audit_table
[2024-06-25T09:47:39.423+0000] {skipmixin.py:178} INFO - Following branch insert_new_record_into_audit_table
[2024-06-25T09:47:39.441+0000] {skipmixin.py:246} INFO - Skipping tasks [('skipped_due_to_data_unavailability', -1)]
[2024-06-25T09:47:39.464+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-25T09:47:39.491+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=demo_dag_for_alerting_apis_final, task_id=check_data_in_stream, run_id=manual__2024-06-25T09:47:33.926111+00:00, execution_date=20240625T094733, start_date=20240625T094739, end_date=20240625T094739
[2024-06-25T09:47:39.539+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-25T09:47:39.570+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-25T09:47:39.572+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
