[2024-06-26T10:30:04.778+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-26T10:30:04.801+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_dag_for_alerting_final.check_data_in_stream scheduled__2024-06-26T10:29:00+00:00 [queued]>
[2024-06-26T10:30:04.809+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_dag_for_alerting_final.check_data_in_stream scheduled__2024-06-26T10:29:00+00:00 [queued]>
[2024-06-26T10:30:04.809+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-06-26T10:30:04.823+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): check_data_in_stream> on 2024-06-26 10:29:00+00:00
[2024-06-26T10:30:04.827+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=6593) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-26T10:30:04.828+0000] {standard_task_runner.py:63} INFO - Started process 6594 to run task
[2024-06-26T10:30:04.829+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'demo_dag_for_alerting_final', 'check_data_in_stream', 'scheduled__2024-06-26T10:29:00+00:00', '--job-id', '4318', '--raw', '--subdir', 'DAGS_FOLDER/demo_dag_for_alerting.py', '--cfg-path', '/tmp/tmp6xwiyq0h']
[2024-06-26T10:30:04.830+0000] {standard_task_runner.py:91} INFO - Job 4318: Subtask check_data_in_stream
[2024-06-26T10:30:04.877+0000] {task_command.py:426} INFO - Running <TaskInstance: demo_dag_for_alerting_final.check_data_in_stream scheduled__2024-06-26T10:29:00+00:00 [running]> on host ced2311e92d2
[2024-06-26T10:30:04.988+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='demo_dag_for_alerting_final' AIRFLOW_CTX_TASK_ID='check_data_in_stream' AIRFLOW_CTX_EXECUTION_DATE='2024-06-26T10:29:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-26T10:29:00+00:00'
[2024-06-26T10:30:04.988+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-26T10:30:05.004+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-06-26T10:30:05.005+0000] {helper_functions.py:114} INFO - Reading encrypted details from ('/opt/***/dags/postgres_connection.py', '/opt/***/dags/***_api_configuration.py')
[2024-06-26T10:30:05.011+0000] {helper_functions.py:117} INFO - Decrypted postgres connection: {'user': '***', 'password': '***', 'dbname': '***', 'host': '172.240.4.3', 'port': '5432'}
[2024-06-26T10:30:05.015+0000] {helper_functions.py:82} INFO - Executing create table SQL
[2024-06-26T10:30:05.016+0000] {helper_functions.py:86} INFO - Checking existing record for dag_id and task_id
[2024-06-26T10:30:05.017+0000] {helper_functions.py:103} INFO - Inserting new record for demo_dag_for_alerting_final - check_data_in_stream
[2024-06-26T10:30:05.017+0000] {helper_functions.py:107} ERROR - Failed to update database for demo_dag_for_alerting_final - check_data_in_stream: can't execute an empty query
Traceback (most recent call last):
  File "/opt/airflow/dags/helper_functions.py", line 104, in update_database
    cur.execute(self.insert_query, (dag_id, task_id, current_time))
psycopg2.ProgrammingError: can't execute an empty query
[2024-06-26T10:30:05.019+0000] {python.py:237} INFO - Done. Returned value was: insert_new_record_into_audit_table
[2024-06-26T10:30:05.019+0000] {branch.py:36} INFO - Branch into insert_new_record_into_audit_table
[2024-06-26T10:30:05.020+0000] {skipmixin.py:178} INFO - Following branch insert_new_record_into_audit_table
[2024-06-26T10:30:05.035+0000] {skipmixin.py:246} INFO - Skipping tasks [('skipped_due_to_data_unavailability', -1)]
[2024-06-26T10:30:05.057+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-26T10:30:05.078+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=demo_dag_for_alerting_final, task_id=check_data_in_stream, run_id=scheduled__2024-06-26T10:29:00+00:00, execution_date=20240626T102900, start_date=20240626T103004, end_date=20240626T103005
[2024-06-26T10:30:05.122+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-26T10:30:05.158+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-26T10:30:05.160+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
