[2024-06-25T12:08:02.202+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-25T12:08:02.228+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_dag_for_alerting_final_1.check_previous_run_status scheduled__2024-06-25T12:07:00+00:00 [queued]>
[2024-06-25T12:08:02.237+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_dag_for_alerting_final_1.check_previous_run_status scheduled__2024-06-25T12:07:00+00:00 [queued]>
[2024-06-25T12:08:02.237+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-06-25T12:08:02.250+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): check_previous_run_status> on 2024-06-25 12:07:00+00:00
[2024-06-25T12:08:02.257+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1232) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-25T12:08:02.258+0000] {standard_task_runner.py:63} INFO - Started process 1233 to run task
[2024-06-25T12:08:02.258+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'demo_dag_for_alerting_final_1', 'check_previous_run_status', 'scheduled__2024-06-25T12:07:00+00:00', '--job-id', '3865', '--raw', '--subdir', 'DAGS_FOLDER/demo_dag_for_alerting.py', '--cfg-path', '/tmp/tmpx2tftyv_']
[2024-06-25T12:08:02.259+0000] {standard_task_runner.py:91} INFO - Job 3865: Subtask check_previous_run_status
[2024-06-25T12:08:02.301+0000] {task_command.py:426} INFO - Running <TaskInstance: demo_dag_for_alerting_final_1.check_previous_run_status scheduled__2024-06-25T12:07:00+00:00 [running]> on host ced2311e92d2
[2024-06-25T12:08:02.396+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='demo_dag_for_alerting_final_1' AIRFLOW_CTX_TASK_ID='check_previous_run_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T12:07:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-25T12:07:00+00:00'
[2024-06-25T12:08:02.396+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-25T12:08:02.409+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-06-25T12:08:02.410+0000] {helper_functions.py:63} INFO - Executing check_last_run_status for DAG: demo_dag_for_alerting_final_1, Task: check_previous_run_status
[2024-06-25T12:08:02.410+0000] {helper_functions.py:113} ERROR - Failed to run demo_dag_for_alerting_final_1 with task check_previous_run_status: 
[2024-06-25T12:08:02.410+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-25T12:08:02.412+0000] {branch.py:36} INFO - Branch into None
[2024-06-25T12:08:02.412+0000] {skipmixin.py:178} INFO - Following branch None
[2024-06-25T12:08:02.426+0000] {skipmixin.py:246} INFO - Skipping tasks [('skip_run', -1), ('start_run', -1)]
[2024-06-25T12:08:02.448+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-25T12:08:02.456+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=demo_dag_for_alerting_final_1, task_id=check_previous_run_status, run_id=scheduled__2024-06-25T12:07:00+00:00, execution_date=20240625T120700, start_date=20240625T120802, end_date=20240625T120802
[2024-06-25T12:08:02.471+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-25T12:08:02.495+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-25T12:08:02.500+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
